### ISSUE TITLE
build ASAP viewer with Qt 5.15

### ISSUE THREAD

**Issue by hubutui** [computationalpathologygroup/ASAP#176]
I got this error when build with Qt 5.15
```
/home/hubutui/Projects/archlinuxcn-repo/archlinuxcn/asap/src/asap/ASAP/MiniMap.cpp: In member function ‘virtual void MiniMap::paintEvent(QPaintEvent*)’:
/home/hubutui/Projects/archlinuxcn-repo/archlinuxcn/asap/src/asap/ASAP/MiniMap.cpp:75:20: error: aggregate ‘QPainterPath bck’ has incomplete type and cannot be defined
   75 |       QPainterPath bck;
      |                    ^~~
/home/hubutui/Projects/archlinuxcn-repo/archlinuxcn/asap/src/asap/ASAP/MiniMap.cpp:81:16: error: invalid use of incomplete type ‘const class QPainterPath’
   81 |         if (!it->isEmpty()) {
      |                ^~
```
According to [this link](https://github.com/RPCS3/rpcs3/pull/7832), we need to include `QPainterPath`. And it fixed this issue.
